# Generated by Django 4.0.4 on 2022-06-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeserie',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
