# Generated by Django 4.0.4 on 2022-06-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Playground', '0004_alter_mangacomic_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimeSerie',
            new_name='SeriePelicula',
        ),
    ]
