# Generated by Django 4.0.4 on 2022-06-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Playground', '0005_rename_animeserie_seriepelicula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
